version: '3.8'
services:
  postgis_10_25:
    image: postgis/postgis:10-2.5-alpine
    ports:
    - "5557:5432"
    env_file:
      - postgis.env
    volumes:
      - postgis_10_25-data:/var/lib/postgresql/data/
      - "./_init_db3dnl.sql:/docker-entrypoint-initdb.d/_init_db3dnl.sql:ro"
      - "./Kadaster3DBVDB/:/docker-entrypoint-initdb.d/"
    networks:
      - cjdb-network
  postgis_15_33:
    image: postgis/postgis:15-3.3-alpine
    ports:
    - "5558:5432"
    env_file:
      - postgis.env
    volumes:
      - postgis_15_33-data:/var/lib/postgresql/data/
      - "./_init_db3dnl.sql:/docker-entrypoint-initdb.d/_init_db3dnl.sql:ro"
      - "./Kadaster3DBVDB/:/docker-entrypoint-initdb.d/"
#      - "./db3dnl_sample.sql.gz:/docker-entrypoint-initdb.d/db3dnl_sample.sql.gz:ro"
    networks:
      - cjdb-network
volumes:
  postgis_10_25-data:
  postgis_15_33-data:
networks:
  cjdb-network:
